Large reorg of the docs
linuxserver/docker-documentation pull request #17
Opened 2020-09-16 13:53 UTC by IronicBadger

This PR supports the one made to the README templates yesterday.

https://github.com/linuxserver/docker-jenkins-builder/pull/57

The gist is "less is more" in the READMEs and a lot of the repetitive information belongs better in this documentation repository.

2020-10-21 07:48 UTC, JoshStark commented
Overall looks good to me. Only point I can think of is that while Fleet is used by us to show our image list, it’s not just for us, so it may be worth making it clearer in the title for the Fleet Docs that it’s just that; documentation on setting up Fleet. 

Other than that, looks good.

2020-10-23 15:36 UTC, aptalca commented
although a reorganization is nice and needed, these changes will break a lot of inbound links we have in various places

2021-01-03 16:37 UTC, IronicBadger commented
@aptalca i would like to offer to handle the documentation as a whole if possible. It needs a bit of love here and there, and that would include fixing links in readme's and stuff like that elsewhere.

Will obviously need a little help doing that from the outside though.

2021-01-06 13:14 UTC, nemchik requested changes
Just a few things suggested to revert so we preserve the permalinks. Trying to get some initial feedback put in, but I have not yet proof-read the new additions (building locally and auto update). I will do a second review on those.

2021-01-06 13:14 UTC, nemchik commented on SUMMARY.md
> +## Container 101
```suggestion
## General
```
Possibly indicate that this could serve as a "Container 101" underneath the heading so that the permalink remains in tact.

2021-01-06 13:14 UTC, nemchik commented on container-101/container-debugging.md
> +# Container Debugging
```suggestion
# Container Execution
```
Let's keep the headings so the permalinks remain unchanged.

2021-01-06 13:14 UTC, nemchik commented on container-101/container-debugging.md
> +## "Exec" into a specific container
```suggestion
## Shell Access
```
Let's keep the headings so the permalinks remain unchanged.

2021-01-06 13:29 UTC, nemchik commented
Also my review didn't address the files and folders being renamed. Those would need to be put back in their original locations in order to fully resolve my first review.

2022-08-08 21:51 UTC, ironicbadger commented
Stale. Forgotten. Old. Pointless.

2022-08-08 21:51 UTC, closed without merging

2022-10-04 15:21 UTC, drizuid commented
> Stale. Forgotten. Old. Pointless.

I didn't realize you had forgotten about this or lost interest, I had actually thought this was still open while you worked towards your goal.  I quite liked the idea. I hope at some point you come back and finish what you suggested and follow through, but I know real life can get in the way sometimes :( Just keep in mind for the future, if you commit to something and something prevents you from doing it, that is fine, but you should at least notify people.